ruby/homework/blog/config/routes.rb
Rails.application.routes.draw do
  resources :donations
  devise_for :users
  get "donations/new"
  get "donations/create"
  # resources :cate_twos
  # resources :category_twos
  root "categories#index"
  
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  resources :categories 

  resources :donations, only: [:new, :create]
  
    resources :articles do
      resources :comments
    end
  resources :authors
  
end

ruby/homework/blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ruby/homework/blog/app/models/article.rb
class Article < ApplicationRecord
    belongs_to :author
    belongs_to :category, optional: false
    has_many :comments, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end
  

ruby/homework/blog/app/models/author.rb
class Author < ApplicationRecord
    has_many :articles
end

ruby/homework/blog/app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true
  validates :description, presence: true

end

ruby/homework/blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

ruby/homework/blog/app/models/donation.rb
class Donation < ApplicationRecord
end

ruby/homework/blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  validates :first_name, :last_name, presence: true
  validates :username, presence: true, uniqueness: true
   
end

ruby/homework/blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
    end
    
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  
end

ruby/homework/blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @articles = Article.all
  
  end

  def show
    @article = Article.find(params[:id])
    @author = Author.all
    @category = @article.category
  end

  def new
    @article = Article.new
    @categories = Category.all
    @author = Author.all
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      @author = Author.all
      @categories = Category.all
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
    @categories = Category.all
    @author = Author.all
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      @categories = Category.all
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :category_id, :author_id)
    end

end

ruby/homework/blog/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController 

    def index
        @author = Author.all

    end

    def show 
        @author = Author.find(params[:id])
    end

    def new 
        @author = Author.new
    end

    def create
        @author = Author.new(author_params)
    
        if @author.save
          redirect_to @author
        else
          render :new, status: :unprocessable_entity
        end
    end
    def edit
      @author = Author.find(params[:id])
    end


    def update
      @author = Author.find(params[:id])
  
      if @author.update(author_params)
        redirect_to @author
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @author = Author.find(params[:id])
      @author.destroy
  
      redirect_to root_path, status: :see_other
    end




    private
    def author_params
      params.require(:author).permit(:name, :bio)
    end
end

ruby/homework/blog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: :index
    def index
      @categories = Category.all
    end
  
    def show
      @category = Category.find(params[:id])
      @articles = Article.all
      @author = Author.all
    end
  
    def new
      @category = Category.new
    end
  
    def create
      @category = Category.new(categories_params)
  
      if @category.save
        redirect_to @category
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def edit
      @category = Category.find(params[:id])
    end
  
    def update
      @category = Category.find(params[:id])
  
      if @category.update(categories_params)
        redirect_to @category
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      @category = Category.find(params[:id])
      @category.destroy
  
      redirect_to root_path, status: :see_other
    end



    private
      def categories_params
        params.require(:category).permit(:name, :description)
      end
  end

ruby/homework/blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: :destroy
    
    def create
      @article = Article.find(params[:article_id])
      @comment = @article.comments.create(comment_params)
      redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: :see_other
      end
  
    private
      def comment_params
        params.require(:comment).permit(:commenter, :body)
      end
  end
  

ruby/homework/blog/app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def create
    Stripe::PaymentIntent.create({
      amount: (params[:amount].to_i * 100), # Amount in cents
      currency: 'usd',
      payment_method: params[:payment_method_id],
      confirm: true,
      automatic_payment_methods: { enabled: true, allow_redirects: 'never' }
    })

    redirect_to root_path, notice: "Thank you for your donation!"
    rescue Stripe::CardError => e
    redirect_to new_donation_path, alert: e.message

    Stripe::Subscription.create({
      customer: users.id ,
      items: [{ price: ENV['STRIPE_PRICE_ID'] }],
    })
    @donation.stripe_subscription_id = subscription.id
    @donation.save!
  end


end

ruby/homework/blog/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/homework/blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

ruby/homework/blog/app/helpers/cate_twos_helper.rb
module CateTwosHelper
end

ruby/homework/blog/app/helpers/categories_helper.rb
module CategoriesHelper
end

ruby/homework/blog/app/helpers/category_descriptions_helper.rb
module CategoryDescriptionsHelper
end

ruby/homework/blog/app/helpers/category_helper.rb
module CategoryHelper
end

ruby/homework/blog/app/helpers/category_twos_helper.rb
module CategoryTwosHelper
end

ruby/homework/blog/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/homework/blog/app/helpers/donations_helper.rb
module DonationsHelper
end

ruby/homework/blog/app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :body %><br>
      <%= form.text_area :body %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
        <%= form.label :category %><br>
        <%= form.select :category_id, @categories.collect { |c| [c.name, c.id] }, prompt: "Select a Category" %>
    <div>
    <div>
        <%= form.label :author %><br>
        <%= form.select :author_id, @author.collect { |c| [c.name, c.id] }, prompt: "Select a Author" %>
    <div>
      <%= form.submit %>
    </div>
  <% end %>

ruby/homework/blog/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

ruby/homework/blog/app/views/articles/index.html.erb
<% if user_signed_in? %>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= button_to "Sign In", user_session_path %>
<% end %>

<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

ruby/homework/blog/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

ruby/homework/blog/app/views/articles/show.html.erb
<% content_for :javascript do %>
  <script type="module">
    import "add_jquery";
  </script>
  <% end %>

<h1 class = header><%= @article.title %></h1>

<div id="article-content">
<em><p class = description><%= @article.body %></p></em>



<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2>Comments</h2>

<div id="comments">
<!-- append here -->
</div>

<button id="load-comments" 
        data-article="<%= @article.id %>" 
        data-category="<%= @article.category.id %>">
  Load More Comments
</button>

<h2>Add a comment:</h2>
<%= render "comments/form", article: @article %>
</div>


<%= link_to "Home", root_path %>

<button id = "toggle-content-button"> Hide Content </button>

ruby/homework/blog/app/views/authors/_form.html.erb
<h1>New Author</h1>

<%= form_with model: @author do |form| %>

  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>
<br>
  <%= form.submit "Create Author" %>
<% end %>

ruby/homework/blog/app/views/authors/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", author: @author %>

ruby/homework/blog/app/views/authors/index.html.erb
<h1>Authors</h1>

<ul>
  <% @author.each do |author| %>
    <li>
      <%= link_to author.name, author %>
    </li>
  <% end %>
</ul>

<%= link_to "New Author", new_author_path %>

ruby/homework/blog/app/views/authors/new.html.erb
<%= render "form", authors: @author %>

ruby/homework/blog/app/views/authors/show.html.erb
<h1 class = header><%= @author.name %></h1>

<em><p class = description><%= @author.bio %></p></em>

<ul>
  <li><%= link_to "Edit", edit_author_path(@author) %></li>
  <li><%= link_to "Destroy", author_path(@author), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2 class = header>Articles</h2>

<%= link_to "Home", root_path %>

ruby/homework/blog/app/views/categories/_form.html.erb
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>
<%= link_to "New Category", new_category_path %>

ruby/homework/blog/app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_with model: @category do |form| %>

  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<br>
  <%= form.submit "Update Category" %>
<% end %>

ruby/homework/blog/app/views/categories/index.html.erb
<div class = header> <h1> CATEGORY LIST <h1> </div>

<div class="user-info">
<% if user_signed_in? %>
  Welcome <%= current_user.username %>
  <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "auth-button" %>
<% else %>
  <%= button_to "Sign In", user_session_path, class: "auth-button" %>
<% end %>
</div>

<ul>
  <% @categories.each do |category| %>
      <li class = "category_name">
        <%= link_to category.name, category %>
      </li>
    
    <p class ="description"><em><%= category.description %></em></p>

    <p>Number of articles: <%= category.articles.count %></p>
    
  <% end %>
</ul>

<%= link_to "New Category", new_category_path %><br>
<%= link_to "New Article", new_article_path %><br>
<%= link_to "New Author", new_author_path %><br>
<br>
<%= link_to "Support Us!", new_donation_path %>

ruby/homework/blog/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_with model: @category do |form| %>

  
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>
<br>
  <%= form.submit "Create Category" %>
<% end %>

ruby/homework/blog/app/views/categories/show.html.erb
<h1 class = header><%= @category.name %></h1>
<h3 class = description><em><%= @category.description %></em></h3>

<%= link_to "Home", root_path %>

<ul>
  <li><%= link_to "Edit", edit_category_path(@category) %></li>
  <li><%= link_to "Destroy", category_path(@category), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

<h2 class = header>Articles</h2>

  <% @articles.each do |article| %>
    <ul>
      <%= link_to article.title, article_path(article) if article.category_id == @category.id %>

    </ul>
  <% end %>

  <br> 

  <%= link_to "Create a New Article", new_article_path %>

ruby/homework/blog/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
    <%= link_to "Destroy Comment", [comment.article, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>

ruby/homework/blog/app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>
    <p>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
  <% end %>

ruby/homework/blog/app/views/donations/_form.html.erb
<%= form_with model: @donations do |form| %>
  <div class="field">
    <%= form.label :recurring, "Make this a monthly donation" %>
    <%= form.check_box :recurring %>
  </div>
  <%= form.submit %>
  <% end %>

ruby/homework/blog/app/views/donations/create.html.erb
<h1>Donations#create</h1>
<p>Find me in app/views/donations/create.html.erb</p>

ruby/homework/blog/app/views/donations/new.html.erb
<%= javascript_include_tag "donation", type: "module" %> <!-- Load the donation.js.erb file -->

<h1>Support Our Blog</h1>
<div class = "donation-container">
<%= form_with url: donations_path, method: :post, local: true, id: "payment-form" do |form| %>
  <%= form.hidden_field :csrf_token, value: form_authenticity_token %> <!-- Ensure the CSRF token is included -->

  <label for="amount">Donation Amount:</label>
  <input type="number" name="amount" min="1" required />

  <div id="card-container">
  <label for="card-element">Credit or Debit Card:</label>
  <div id="card-element"><!-- Stripe will place the card input here --></div>
  </div> 

  <button type="submit">Donate</button> <%= render "form", donation: @donation %>
<% end %>
</div>

<h1> Email </h1>
<%= form_with model: @user, local: true do |form| %>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  
  <div class="form-group">
    <%= form.submit 'Confirm Email', class: 'btn btn-primary' %>
  </div>
<br>
<% end %>